// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "test-docker-k8s-swagger/models"
)

// GetReadyzOKCode is the HTTP code returned for type GetReadyzOK
const GetReadyzOKCode int = 200

/*GetReadyzOK OK

swagger:response getReadyzOK
*/
type GetReadyzOK struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetReadyzOK creates GetReadyzOK with default headers values
func NewGetReadyzOK() *GetReadyzOK {

	return &GetReadyzOK{}
}

// WithPayload adds the payload to the get readyz o k response
func (o *GetReadyzOK) WithPayload(payload *models.GeneralResponse) *GetReadyzOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get readyz o k response
func (o *GetReadyzOK) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReadyzOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
