// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Test Service
Test API


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0
    Contact: Test API Support

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
