swagger: '2.0'
info:
  title: Test Service
  description: Test API
  contact:
    name: Test API Support
  version: 1.0.0
schemes: [
  "http"
]
consumes: [
  "application/json"
]
produces: [
  "application/json"
]
paths:
  /:
    $ref: ./paths/default.yml
  /healthz:
    $ref: ./paths/healthz.yml
  /readyz:
    $ref: ./paths/readyz.yml
